[workspace]
members = ["hwctl", "hwlib"]
resolver = "2"
exclude = ["debian", "rust-vendor"]

[workspace.package]
version = "0.9.2"
edition = "2021"
authors = [
    "Canonical Hardware Certification <canonical-hw-cert@lists.launchpad.net>",
    "Nadzeya Hutsko <nadzeya.hutsko@canonical.com>",
    "Matias Piipari <matias.piipari@canonical.com>",
]
documentation = "https://github.com/canonical/hardware-api/"
homepage = "https://github.com/canonical/hardware-api/"
repository = "https://github.com/canonical/hardware-api/"

[workspace.dependencies]
anyhow = "~1.0.0"
serde_json = "~1.0.0"

[workspace.metadata.vendor-filter]
platforms = ["x86_64-unknown-linux-gnu", "aarch64-unknown-linux-gnu"]
tier = "2"
all-features = false
exclude-crate-paths = [ { name = "*", exclude = "tests" },
			{ name = "*", exclude = "examples" },
                        { name = "*", exclude = "test-data" },
                      ]
