name: hwctl
adopt-info: hwctl
summary: Canonical Certified Hardware API Client
description: |
  hwctl is a hwlib backed CLI tool for collecting and sending hardware
  information to hwapi to find testing status of device models

source-code: https://github.com/canonical/hardware-api
issues: https://github.com/canonical/hardware-api/issues
contact: https://github.com/canonical/hardware-api/issues

base: core22
grade: stable
confinement: strict

architectures:
  - build-on: [amd64]

apps:
  hwctl:
    command: hwctl
    plugs:
      - network
      - hardware-observe
      - system-observe
      - network-setup-observe
      - kernel-module-observe
      - hardware-control

parts:
  hwctl:
    plugin: rust
    source: .
    build-packages:
      - pkg-config
      - libssl-dev
      - jq
    override-pull: |
      craftctl default
      metadata="$(cargo metadata --no-deps --format-version 1)"
      version="$(echo "$metadata" | jq -r .packages[0].version)"
      craftctl set version="$version"
