[package]
name = "hwctl"
description = "hwlib backed CLI tool for collecting and sending hardware information to hi-api to find testing status of device models"
license = "GPL-3.0-only"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "=1.29.1", features = ["full"] }
hwlib = { path = "../hwlib", version = "0.0.1" }
