repos:
-   repo: local
    hooks:
    -   id: openapi-fetch
        name: Fetch OpenAPI YAML
        entry: scripts/fetch_openapi.sh
        language: script
        always_run: true
        pass_filenames: false
