repos:
-   repo: local
    hooks:
    - id: openapi-fetch-yaml
      name: Fetch OpenAPI YAML
      entry: scripts/fetch_openapi_yaml.sh
      language: script
      always_run: true
      pass_filenames: false
