[package]
name = "hwlib"
description = "Collects and sends hardware information to hwapi to find testing status of the device model"
license = "GPL-3.0-only"
version = "0.9.2"
edition = "2021"
authors = [
  "Canonical Hardware Certification <canonical-hw-cert@lists.launchpad.net>",
  "Nadzeya Hutsko <nadzeya.hutsko@canonical.com>",
  "Matias Piipari <matias.piipari@canonical.com>",
]
documentation = "https://github.com/canonical/hardware-api/"
homepage = "https://github.com/canonical/hardware-api/"
repository = "https://github.com/canonical/hardware-api/"
exclude = ["debian/*",]

[lib]
name = "hwlib"
crate-type = [ "cdylib", "rlib",]

[dependencies]
os-release = { version = "0.1.0" }
serde_json = "~1.0.0"
reqwest = { version = "0.12.0", features = ["json"] }
serde = { version = "~1.0.0", features = ["derive"] }
tokio = { version = "1.43.1", features = ["rt", "rt-multi-thread", "test-util"], default-features = false }
pyo3 = { version = "0.24.0", features = ["extension-module"] }
smbios-lib = "0.9.0"
regex = "1.10.0"
time = { version = "~0.3.0", features = ["macros" ,"parsing", "formatting"]}
anyhow = "~1.0.0"
itertools = "0.14.0"
lazy_static = "1.5.0"

[dev-dependencies]
simple_test_case = "1.2.0"
pretty_assertions = "1.4.1"

[package.metadata.deb]
maintainer = "Canonical Hardware Certification <canonical-hw-cert@lists.launchpad.net>"
copyright = "Copyright 2024 Canonical Ltd."
