[package]
name = "hwlib"
description = "collects and sends hardware information to hwapi to find testing status of the device model"
license = "GPL-3.0-only"
version = "0.0.1"
edition = "2021"
authors = []

[dependencies]
serde_json = "=1.0.103"
once_cell = "=1.18.0"

[lib]
name = "hwlib"
crate-type = [ "cdylib", "rlib",]

[dependencies.reqwest]
version = "=0.11.25"
features = [ "json",]

[dependencies.serde]
version = "=1.0.171"
features = [ "derive",]

[dependencies.tokio]
version = "=1.29.1"
features = [ "full", "test-util",]

[dependencies.pyo3]
version = "=0.19.0"
features = [ "extension-module",]

[package.metadata.deb]
maintainer = "Canonical Hardware Certification <canonical-hw-cert@lists.launchpad.net>"
copyright = "Copyright 2024 Canonical Ltd."
