[package]
name = "hwlib"
description = "collects and sends hardware information to hwapi to find testing status of the device model"
license = "GPL-3.0-only"
version = "0.1.0"
edition = "2021"
authors = []
documentation = "https://github.com/canonical/hardware-api/"
homepage = "https://github.com/canonical/hardware-api/"
repository = "https://github.com/canonical/hardware-api/"
exclude = ["debian/*",]

[package.metadata.vendor-filter]
platforms = ["*-unknown-linux-gnu"]
tier = "2"
all-features = false

[lib]
name = "hwlib"
crate-type = [ "cdylib", "rlib",]

[target.'cfg(all(target_os = "linux"))'.dependencies]
serde_json = "1.0.41"
once_cell = "1.19.0"
reqwest = { version = "0.12.0", features = [ "json",] }
serde = { version = "1.0.104", features = [ "derive",] }
tokio = { version = "1.38.0", features = [ "full", "test-util",], default-features = false }
pyo3 = { version = "0.21.2", features = [ "extension-module",] }

[package.metadata.deb]
maintainer = "Canonical Hardware Certification <canonical-hw-cert@lists.launchpad.net>"
copyright = "Copyright 2024 Canonical Ltd."
