[package]
name = "hwlib"
description = "collects and sends hardware information to hwapi to find testing status of the device model"
license = "GPL-3.0-only"
version = "0.1.0"
edition = "2021"
authors = []

[package.metadata.deb]
maintainer = "Canonical Hardware Certification <canonical-hw-cert@lists.launchpad.net>"
copyright = "Copyright 2024 Canonical Ltd."

[dependencies]
reqwest = { version = "=0.11.18", features = ["json"] }
serde = { version = "=1.0.171", features = ["derive"] }
tokio = { version = "=1.36.0", features = ["full", "test-util"] }
serde_json = "=1.0.103"
pyo3 = { version = "=0.19.0", features = ["extension-module"] }
once_cell = "=1.18.0"

[lib]
name = "hwlib"
crate-type = ["cdylib", "rlib"]
