components:
  schemas:
    AudioValidator:
      description: Validator model for audio devices
      properties:
        identifier:
          title: Identifier
          type: string
        model:
          title: Model
          type: string
        vendor:
          title: Vendor
          type: string
      required:
      - model
      - vendor
      - identifier
      title: AudioValidator
      type: object
    BiosValidator:
      properties:
        firmware_revision:
          anyOf:
          - type: string
          - type: 'null'
          title: Firmware Revision
        release_date:
          anyOf:
          - format: date
            type: string
          - type: 'null'
          title: Release Date
        revision:
          anyOf:
          - type: string
          - type: 'null'
          title: Revision
        vendor:
          title: Vendor
          type: string
        version:
          title: Version
          type: string
      required:
      - vendor
      - version
      - revision
      - firmware_revision
      - release_date
      title: BiosValidator
      type: object
    BoardValidator:
      properties:
        manufacturer:
          title: Manufacturer
          type: string
        product_name:
          title: Product Name
          type: string
        version:
          title: Version
          type: string
      required:
      - manufacturer
      - product_name
      - version
      title: BoardValidator
      type: object
    CertificationStatusRequest:
      description: Request body validator for status check endpoint
      properties:
        architecture:
          title: Architecture
          type: string
        audio:
          anyOf:
          - items:
              $ref: '#/components/schemas/AudioValidator'
            type: array
          - type: 'null'
          title: Audio
        bios:
          anyOf:
          - $ref: '#/components/schemas/BiosValidator'
          - type: 'null'
        board:
          $ref: '#/components/schemas/BoardValidator'
        chassis:
          anyOf:
          - $ref: '#/components/schemas/ChassisValidator'
          - type: 'null'
        gpu:
          anyOf:
          - items:
              $ref: '#/components/schemas/GPUValidator'
            type: array
          - type: 'null'
          title: Gpu
        model:
          title: Model
          type: string
        network:
          anyOf:
          - items:
              $ref: '#/components/schemas/NetworkAdapterValidator'
            type: array
          - type: 'null'
          title: Network
        os:
          anyOf:
          - $ref: '#/components/schemas/OSValidator'
          - type: 'null'
        pci_peripherals:
          default: []
          items:
            $ref: '#/components/schemas/PCIPeripheralValidator'
          title: Pci Peripherals
          type: array
        processor:
          default: []
          items:
            $ref: '#/components/schemas/ProcessorValidator'
          title: Processor
          type: array
        usb_peripherals:
          default: []
          items:
            $ref: '#/components/schemas/USBPeripheralValidator'
          title: Usb Peripherals
          type: array
        vendor:
          title: Vendor
          type: string
        video:
          anyOf:
          - items:
              $ref: '#/components/schemas/VideoCaptureValidator'
            type: array
          - type: 'null'
          title: Video
        wireless:
          anyOf:
          - items:
              $ref: '#/components/schemas/WirelessAdapterValidator'
            type: array
          - type: 'null'
          title: Wireless
      required:
      - vendor
      - model
      - architecture
      - board
      title: CertificationStatusRequest
      type: object
    CertifiedResponse:
      description: 'If a system is certified, we return the information about OS and
        bios

        used on the system under test we had in the lab to certify the machine'
      properties:
        bios:
          anyOf:
          - $ref: '#/components/schemas/BiosValidator'
          - type: 'null'
        os:
          $ref: '#/components/schemas/OSValidator'
        status:
          const: Certified
          default: Certified
          enum:
          - Certified
          title: Status
          type: string
      required:
      - os
      - bios
      title: CertifiedResponse
      type: object
    ChassisValidator:
      properties:
        chassis_type:
          title: Chassis Type
          type: string
        manufacturer:
          title: Manufacturer
          type: string
        sku:
          title: Sku
          type: string
        version:
          title: Version
          type: string
      required:
      - chassis_type
      - manufacturer
      - sku
      - version
      title: ChassisValidator
      type: object
    GPUValidator:
      properties:
        family:
          anyOf:
          - type: string
          - type: 'null'
          title: Family
        identifier:
          title: Identifier
          type: string
        manufacturer:
          title: Manufacturer
          type: string
        version:
          title: Version
          type: string
      required:
      - manufacturer
      - version
      - identifier
      title: GPUValidator
      type: object
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          title: Detail
          type: array
      title: HTTPValidationError
      type: object
    KernelPackageValidator:
      properties:
        name:
          anyOf:
          - type: string
          - type: 'null'
          title: Name
        signature:
          anyOf:
          - type: string
          - type: 'null'
          title: Signature
        version:
          title: Version
          type: string
      required:
      - name
      - version
      - signature
      title: KernelPackageValidator
      type: object
    NetworkAdapterValidator:
      description: Validator for ethernet network adapters
      properties:
        bus:
          title: Bus
          type: string
        capacity:
          title: Capacity
          type: integer
        identifier:
          title: Identifier
          type: string
        model:
          title: Model
          type: string
        vendor:
          title: Vendor
          type: string
      required:
      - bus
      - identifier
      - model
      - vendor
      - capacity
      title: NetworkAdapterValidator
      type: object
    NotCertifiedResponse:
      properties:
        status:
          const: Not Seen
          default: Not Seen
          enum:
          - Not Seen
          title: Status
          type: string
      title: NotCertifiedResponse
      type: object
    OSValidator:
      properties:
        codename:
          title: Codename
          type: string
        distributor:
          title: Distributor
          type: string
        kernel:
          $ref: '#/components/schemas/KernelPackageValidator'
        loaded_modules:
          items:
            type: string
          title: Loaded Modules
          type: array
        version:
          title: Version
          type: string
      required:
      - distributor
      - version
      - codename
      - kernel
      - loaded_modules
      title: OSValidator
      type: object
    PCIPeripheralValidator:
      properties:
        name:
          title: Name
          type: string
        pci_id:
          title: Pci Id
          type: string
        vendor:
          title: Vendor
          type: string
      required:
      - pci_id
      - name
      - vendor
      title: PCIPeripheralValidator
      type: object
    ProcessorValidator:
      properties:
        family:
          title: Family
          type: string
        frequency:
          title: Frequency
          type: number
        manufacturer:
          title: Manufacturer
          type: string
        version:
          title: Version
          type: string
      required:
      - family
      - frequency
      - manufacturer
      - version
      title: ProcessorValidator
      type: object
    RelatedCertifiedSystemExistsResponse:
      description: 'If a system is partially certified, we return the information
        about components

        were tested on other systems that the machine has'
      properties:
        architecture:
          title: Architecture
          type: string
        audio:
          anyOf:
          - items:
              $ref: '#/components/schemas/AudioValidator'
            type: array
          - type: 'null'
          title: Audio
        board:
          anyOf:
          - $ref: '#/components/schemas/BoardValidator'
          - type: 'null'
        chassis:
          anyOf:
          - $ref: '#/components/schemas/ChassisValidator'
          - type: 'null'
        gpu:
          anyOf:
          - items:
              $ref: '#/components/schemas/GPUValidator'
            type: array
          - type: 'null'
          title: Gpu
        network:
          anyOf:
          - items:
              $ref: '#/components/schemas/NetworkAdapterValidator'
            type: array
          - type: 'null'
          title: Network
        pci_peripherals:
          anyOf:
          - items:
              $ref: '#/components/schemas/PCIPeripheralValidator'
            type: array
          - type: 'null'
          title: Pci Peripherals
        processor:
          anyOf:
          - items:
              $ref: '#/components/schemas/ProcessorValidator'
            type: array
          - type: 'null'
          title: Processor
        status:
          const: Partially Certified
          default: Partially Certified
          enum:
          - Partially Certified
          title: Status
          type: string
        usb_peripherals:
          anyOf:
          - items:
              $ref: '#/components/schemas/USBPeripheralValidator'
            type: array
          - type: 'null'
          title: Usb Peripherals
        video:
          anyOf:
          - items:
              $ref: '#/components/schemas/VideoCaptureValidator'
            type: array
          - type: 'null'
          title: Video
        wireless:
          anyOf:
          - items:
              $ref: '#/components/schemas/WirelessAdapterValidator'
            type: array
          - type: 'null'
          title: Wireless
      required:
      - architecture
      title: RelatedCertifiedSystemExistsResponse
      type: object
    USBPeripheralValidator:
      properties:
        name:
          title: Name
          type: string
        usb_id:
          title: Usb Id
          type: string
        vendor:
          title: Vendor
          type: string
      required:
      - usb_id
      - name
      - vendor
      title: USBPeripheralValidator
      type: object
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          title: Location
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
      type: object
    VideoCaptureValidator:
      description: Validator model for video capture devices
      properties:
        identifier:
          title: Identifier
          type: string
        model:
          title: Model
          type: string
        vendor:
          title: Vendor
          type: string
      required:
      - model
      - vendor
      - identifier
      title: VideoCaptureValidator
      type: object
    WirelessAdapterValidator:
      description: Validator model for wireless network adapters
      properties:
        identifier:
          title: Identifier
          type: string
        model:
          title: Model
          type: string
        vendor:
          title: Vendor
          type: string
      required:
      - model
      - vendor
      - identifier
      title: WirelessAdapterValidator
      type: object
info:
  description: API server for working with hardware information from C3
  title: Hardware API (hwapi)
  version: 1.0.0
openapi: 3.1.0
paths:
  /:
    get:
      operationId: root__get
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: Root
  /v1/certification/status:
    post:
      description: 'Endpoint for checking certification status (whether a system is
        certified, not seen

        or some of its components have been seen on other systems)'
      operationId: check_certification_v1_certification_status_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CertificationStatusRequest'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                anyOf:
                - $ref: '#/components/schemas/CertifiedResponse'
                - $ref: '#/components/schemas/NotCertifiedResponse'
                - $ref: '#/components/schemas/RelatedCertifiedSystemExistsResponse'
                title: Response Check Certification V1 Certification Status Post
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Check Certification
      tags:
      - certification
