name: Documentation
description: Submit a documentation request
type: task
labels: documentation
body:
  - type: checkboxes
    id: check-existing-issues
    attributes:
      label: Check existing issues
      options:
        - label: I've verified that this request isn't described by any existing issues.
          required: true
  - type: textarea
    id: description
    attributes:
      label: Request
      placeholder: >
        A clear and concise description of the request and the problem it solves.
        Include any relevant context, screenshots, or examples.
    validations:
      required: true
  - type: input
    id: page-name
    attributes:
      label: Documentation location
      description: Provide the path of the relevant page
      placeholder: tutorial/setup-guide
