name: Task
description: Submit a feature request
type: task
body:
  - type: checkboxes
    id: check-existing-issues
    attributes:
      label: Check existing issues
      options:
        - label: I've verified that this request isn't described by any existing issues.
          required: true
  - type: textarea
    id: what
    attributes:
      label: Request
      placeholder: >
        A clear and concise description of the feature you'd like to see implemented.
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Motivation
      description: The problem it solves
      placeholder: >
        A clear and concise explanation of the impact your request would have.
    validations:
      required: true
