# Server Charm sub-commands.
mod charm

[doc('Describe usage and list the available recipes.')]
help:
    @echo '{{ BOLD }}Canonical Hardware API Server{{ NORMAL }}'
    @echo
    @echo 'To run tasks for other sub-projects, run {{ CYAN }}`just ..`{{ NORMAL }}.'
    @echo
    @just --list --unsorted

[doc('Generate OpenAPI schema.')]
[group('project')]
schema:
    @uvx tox run -e schema

[doc('Generate lockfile.')]
[group('venv')]
lock:
    @uv lock

[doc('Check lockfile.')]
[group('venv')]
check-lock:
    @uv lock --check

[doc("Update the project's environment.")]
[group('venv')]
venv:
    @uv sync
    @echo 'Activate the Python environment: {{ CYAN }}source .venv/bin/activate{{ NORMAL }}'

[doc('Format all files.')]
[group('lint')]
format:
    @uvx tox run -e format

[doc('Lint all files.')]
[group('lint')]
lint:
    @uvx tox run -e lint

[doc('Run unit tests.')]
[group('test')]
test:
    @uvx tox run -e unit

[doc('Check OpenAPI schema.')]
[group('test')]
check-schema:
    @uvx tox run -e check-schema

[doc('Run the server.')]
[group('deploy')]
serve:
    @docker compose up --build hwapi-dev

[doc('Tear down local deployment.')]
[group('deploy')]
teardown:
    @docker compose down
