components:
  schemas:
    BiosDTO:
      properties:
        firmware_revision:
          title: Firmware Revision
          type: string
        release_date:
          format: date
          title: Release Date
          type: string
        revision:
          title: Revision
          type: string
        vendor:
          title: Vendor
          type: string
        version:
          title: Version
          type: string
      required:
      - vendor
      - version
      - release_date
      - revision
      - firmware_revision
      title: BiosDTO
      type: object
    BoardDTO:
      properties:
        manufacturer:
          title: Manufacturer
          type: string
        product_name:
          title: Product Name
          type: string
        version:
          title: Version
          type: string
      required:
      - manufacturer
      - product_name
      - version
      title: BoardDTO
      type: object
    CertificationResponse:
      properties:
        bios:
          $ref: '#/components/schemas/BiosDTO'
        board:
          $ref: '#/components/schemas/BoardDTO'
        chassis:
          $ref: '#/components/schemas/ChassisDTO'
        detail:
          $ref: '#/components/schemas/CertificationStatus'
      required:
      - detail
      - chassis
      - bios
      - board
      title: CertificationResponse
      type: object
    CertificationStatus:
      enum:
      - Certified
      - Partially Certified
      - Not Seen
      title: CertificationStatus
      type: string
    ChassisDTO:
      properties:
        chassis_type:
          title: Chassis Type
          type: string
        manufacturer:
          title: Manufacturer
          type: string
        version:
          title: Version
          type: string
      required:
      - manufacturer
      - chassis_type
      - version
      title: ChassisDTO
      type: object
    DeviceDTO:
      properties:
        device_type:
          $ref: '#/components/schemas/DeviceType'
        model:
          title: Model
          type: string
        vendor:
          title: Vendor
          type: string
      required:
      - device_type
      - vendor
      - model
      title: DeviceDTO
      type: object
    DeviceType:
      enum:
      - AUDIO
      - BLUETOOTH
      - CAPTURE
      - CARDREADER
      - CDROM
      - DISK
      - EFI
      - HIDRAW
      - KEYBOARD
      - MOUSE
      - NETWORK
      - OTHER
      - PRINTER
      - CPU
      - SOCKET
      - TOUCHPAD
      - TOUCHSCREEN
      - USB
      - GPU
      - WIFI
      - WWAN
      title: DeviceType
      type: string
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          title: Detail
          type: array
      title: HTTPValidationError
      type: object
    PartialCertificationResponse:
      properties:
        certified_components:
          items:
            $ref: '#/components/schemas/DeviceDTO'
          title: Certified Components
          type: array
        detail:
          $ref: '#/components/schemas/CertificationStatus'
      required:
      - detail
      - certified_components
      title: PartialCertificationResponse
      type: object
    SystemInfoDTO:
      properties:
        devices:
          items:
            $ref: '#/components/schemas/DeviceDTO'
          title: Devices
          type: array
        model:
          title: Model
          type: string
        os_version:
          title: Os Version
          type: string
        vendor:
          title: Vendor
          type: string
      required:
      - os_version
      - vendor
      - model
      - devices
      title: SystemInfoDTO
      type: object
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          title: Location
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
      type: object
info:
  description: API server for working with hardware information from C3
  title: Hardware API (hwapi)
  version: 1.0.0
openapi: 3.1.0
paths:
  /:
    get:
      operationId: root__get
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: Root
  /openapi.yaml:
    get:
      description: OpenAPI schema in TAML format
      operationId: get_openapi_yaml_openapi_yaml_get
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: Get Openapi Yaml
  /v1/certification/status:
    post:
      operationId: check_certification_v1_certification_status_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SystemInfoDTO'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                anyOf:
                - $ref: '#/components/schemas/CertificationResponse'
                - $ref: '#/components/schemas/PartialCertificationResponse'
                title: Response Check Certification V1 Certification Status Post
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Check Certification
      tags:
      - certification
