components:
  schemas:
    AudioDTO:
      description: DTO model for audio devices
      properties:
        model:
          title: Model
          type: string
        vendor:
          title: Vendor
          type: string
      required:
      - model
      - vendor
      title: AudioDTO
      type: object
    BiosDTO:
      properties:
        firmware_revision:
          title: Firmware Revision
          type: string
        release_date:
          format: date
          title: Release Date
          type: string
        revision:
          title: Revision
          type: string
        vendor:
          title: Vendor
          type: string
        version:
          title: Version
          type: string
      required:
      - firmware_revision
      - release_date
      - revision
      - vendor
      - version
      title: BiosDTO
      type: object
    BoardDTO:
      properties:
        manufacturer:
          title: Manufacturer
          type: string
        product_name:
          title: Product Name
          type: string
        version:
          title: Version
          type: string
      required:
      - manufacturer
      - product_name
      - version
      title: BoardDTO
      type: object
    CertificationStatusRequest:
      properties:
        bios:
          $ref: '#/components/schemas/BiosDTO'
        board:
          $ref: '#/components/schemas/BoardDTO'
        chassis:
          $ref: '#/components/schemas/ChassisDTO'
        core_devices:
          $ref: '#/components/schemas/CoreDevicesDTO'
        os:
          $ref: '#/components/schemas/OSDTO'
        pci_peripherals:
          items:
            $ref: '#/components/schemas/PCIPeripheralDTO'
          title: Pci Peripherals
          type: array
        usb_peripherals:
          items:
            $ref: '#/components/schemas/USBPeripheralDTO'
          title: Usb Peripherals
          type: array
      required:
      - os
      - bios
      - board
      - chassis
      - core_devices
      - pci_peripherals
      - usb_peripherals
      title: CertificationStatusRequest
      type: object
    CertifiedResponse:
      description: 'If a system is certified, we return the information about OS and
        bios

        used on the system under test we had in the lab to certify the machine'
      properties:
        bios:
          $ref: '#/components/schemas/BiosDTO'
        os:
          $ref: '#/components/schemas/OSDTO'
        status:
          const: Certified
          title: Status
      required:
      - status
      - os
      - bios
      title: CertifiedResponse
      type: object
    ChassisDTO:
      properties:
        chassis_type:
          title: Chassis Type
          type: string
        manufacturer:
          title: Manufacturer
          type: string
        version:
          title: Version
          type: string
      required:
      - chassis_type
      - manufacturer
      - version
      title: ChassisDTO
      type: object
    CoreDevicesDTO:
      description: "DTO for core devices that includes:\n  - cpu\n  - gpu\n  - ethernet\
        \ and wireless network adapters\n  - audio controllers\n  - video capture\
        \ devices\n\nAll of them are marked optional since some of them may not be\
        \ presented\nin the list of seen/tested/certified devices"
      properties:
        audio:
          anyOf:
          - items:
              $ref: '#/components/schemas/AudioDTO'
            type: array
          - type: 'null'
          title: Audio
        gpu:
          anyOf:
          - $ref: '#/components/schemas/GPUDTO'
          - type: 'null'
        network:
          anyOf:
          - items:
              $ref: '#/components/schemas/NetworkAdapterDTO'
            type: array
          - type: 'null'
          title: Network
        processor:
          anyOf:
          - $ref: '#/components/schemas/ProcessorDTO'
          - type: 'null'
        video:
          anyOf:
          - items:
              $ref: '#/components/schemas/VideoCaptureDTO'
            type: array
          - type: 'null'
          title: Video
        wireless:
          anyOf:
          - items:
              $ref: '#/components/schemas/WirelessAdapterDTO'
            type: array
          - type: 'null'
          title: Wireless
      required:
      - processor
      - gpu
      - network
      - wireless
      - audio
      - video
      title: CoreDevicesDTO
      type: object
    GPUDTO:
      properties:
        family:
          title: Family
          type: string
        manufacturer:
          title: Manufacturer
          type: string
        version:
          title: Version
          type: string
      required:
      - family
      - manufacturer
      - version
      title: GPUDTO
      type: object
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          title: Detail
          type: array
      title: HTTPValidationError
      type: object
    NetworkAdapterDTO:
      description: DTO for ethernet network adapters
      properties:
        capacity:
          title: Capacity
          type: integer
        model:
          title: Model
          type: string
        vendor:
          title: Vendor
          type: string
      required:
      - model
      - vendor
      - capacity
      title: NetworkAdapterDTO
      type: object
    NotCertifiedResponse:
      properties:
        status:
          const: Not Seen
          title: Status
      required:
      - status
      title: NotCertifiedResponse
      type: object
    OSDTO:
      properties:
        codename:
          title: Codename
          type: string
        description:
          title: Description
          type: string
        distributor:
          title: Distributor
          type: string
        kernel:
          $ref: '#/components/schemas/PackageDTO'
        loaded_modules:
          items:
            type: string
          title: Loaded Modules
          type: array
        version:
          title: Version
          type: string
      required:
      - distributor
      - description
      - version
      - codename
      - kernel
      - loaded_modules
      title: OSDTO
      type: object
    PCIPeripheralDTO:
      properties:
        name:
          title: Name
          type: string
        pci_id:
          title: Pci Id
          type: string
        vendor:
          title: Vendor
          type: string
      required:
      - pci_id
      - name
      - vendor
      title: PCIPeripheralDTO
      type: object
    PackageDTO:
      properties:
        name:
          title: Name
          type: string
        version:
          title: Version
          type: string
      required:
      - name
      - version
      title: PackageDTO
      type: object
    PartialCertificationResponse:
      description: 'If a system is partially certified, we return the information
        about components

        were tested on other systems that the machine has'
      properties:
        board:
          $ref: '#/components/schemas/BoardDTO'
        chassis:
          anyOf:
          - $ref: '#/components/schemas/ChassisDTO'
          - type: 'null'
        core_devices:
          $ref: '#/components/schemas/CoreDevicesDTO'
        pci_peripherals:
          anyOf:
          - items:
              $ref: '#/components/schemas/PCIPeripheralDTO'
            type: array
          - type: 'null'
          title: Pci Peripherals
        status:
          const: Partially Certified
          title: Status
        usb_peripherals:
          anyOf:
          - items:
              $ref: '#/components/schemas/USBPeripheralDTO'
            type: array
          - type: 'null'
          title: Usb Peripherals
      required:
      - status
      - board
      - core_devices
      title: PartialCertificationResponse
      type: object
    ProcessorDTO:
      properties:
        family:
          title: Family
          type: string
        frequency:
          title: Frequency
          type: number
        manufacturer:
          title: Manufacturer
          type: string
        version:
          title: Version
          type: string
      required:
      - family
      - frequency
      - manufacturer
      - version
      title: ProcessorDTO
      type: object
    USBPeripheralDTO:
      properties:
        name:
          title: Name
          type: string
        usb_id:
          title: Usb Id
          type: string
        vendor:
          title: Vendor
          type: string
      required:
      - usb_id
      - name
      - vendor
      title: USBPeripheralDTO
      type: object
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          title: Location
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
      type: object
    VideoCaptureDTO:
      description: DTO model for video capture devices
      properties:
        model:
          title: Model
          type: string
        vendor:
          title: Vendor
          type: string
      required:
      - model
      - vendor
      title: VideoCaptureDTO
      type: object
    WirelessAdapterDTO:
      description: DTO model for wireless network adapters
      properties:
        model:
          title: Model
          type: string
        vendor:
          title: Vendor
          type: string
      required:
      - model
      - vendor
      title: WirelessAdapterDTO
      type: object
info:
  description: API server for working with hardware information from C3
  title: Hardware API (hwapi)
  version: 1.0.0
openapi: 3.1.0
paths:
  /:
    get:
      operationId: root__get
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: Root
  /v1/certification/status:
    post:
      operationId: check_certification_v1_certification_status_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CertificationStatusRequest'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                anyOf:
                - $ref: '#/components/schemas/CertifiedResponse'
                - $ref: '#/components/schemas/NotCertifiedResponse'
                - $ref: '#/components/schemas/PartialCertificationResponse'
                title: Response Check Certification V1 Certification Status Post
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Check Certification
      tags:
      - certification
