[doc('Describe usage and list the available recipes.')]
help:
    @echo '{{ BOLD }}Canonical Hardware API Server Charm{{ NORMAL }}'
    @echo
    @echo 'To run tasks for other sub-projects, run {{ CYAN }}`just ..`{{ NORMAL }}.'
    @echo
    @just --list --unsorted

[confirm('Install Juju and prepare environment (destructive)?')]
[doc('Set up integration test environment (destructive).')]
[group('project')]
setup:
    sudo snap install --classic concierge
    sudo concierge prepare --verbose

[doc('Generate lockfile.')]
[group('venv')]
lock:
    @uv lock

[doc('Check lockfile.')]
[group('venv')]
check-lock:
    @uv lock --check

[doc("Update the project's environment.")]
[group('venv')]
venv:
    @uv sync
    @echo 'Activate the Python environment: {{ CYAN }}source .venv/bin/activate{{ NORMAL }}'

[doc('Format all files.')]
[group('lint')]
format:
    @uvx tox run -e format

[doc('Lint all files.')]
[group('lint')]
lint:
    @uvx tox run -e lint

[doc('Run unit tests.')]
[group('test')]
test:
    @uvx tox run -e unit

[arg('logs', long='logs', help='Dump juju logs to this directory.')]
[doc('Run integration tests.')]
[group('test')]
integration logs='': charmcraft
    @uvx tox run -e integration {{ if logs != '' { '-- --juju-dump-logs ' + logs } else { '' } }}

[doc('Build the charm package.')]
[group('package')]
charmcraft:
    @charmcraft pack
