[doc('Describe usage and list the available recipes.')]
help:
    @echo '{{ BOLD }}Canonical Hardware API Documentation{{ NORMAL }}'
    @echo
    @echo 'To run tasks for other sub-projects, run {{ CYAN }}`just ..`{{ NORMAL }}.'
    @echo
    @just --list --unsorted

[doc('Watch, build, and serve the documentation.')]
run:
    make run

[doc('Build documentation.')]
html:
    make html

[doc('Serve built documentation.')]
serve:
    make serve

[doc('Clean built documentation.')]
clean-doc:
    make clean-doc

[doc('Clean full environment.')]
clean:
    make clean

[doc('Check links.')]
linkcheck:
    make linkcheck

[doc('Check spelling.')]
spelling:
    make spelling

[doc('Check inclusive language.')]
woke:
    make woke

[doc('Check accessibility.')]
pa11y:
    make pa11y

[doc('Check style guide compliance.')]
vale:
    make vale
