name: hwctl
base: core22
version: "0.0"
adopt-info: hwctl
summary: Hardware API client
description: Canonical Certified Hardware API client

grade: stable
confinement: strict

apps:
  hwctl:
    command: hwctl
    plugs:
      - network
      - hardware-observe
      - system-observe
      - network-setup-observe
      - kernel-module-observe
      - hardware-control

parts:
  hwctl:
    plugin: rust
    source: https://github.com/canonical/hardware-api.git
    source-branch: main
    source-type: git
    build-packages:
      - pkg-config
      - libssl-dev
    override-pull: |
      craftctl default
      last_committed_tag="$(git describe --tags --abbrev=0)"
      last_committed_tag_ver="$(echo ${last_committed_tag} | sed 's/v//')"

      craftctl set version="$(git describe --tags | sed 's/v//')"
      craftctl set commit="$(git rev-parse HEAD)"
