name: Check Charm Libs on Pull Request
permissions:
  contents: read
on:
  pull_request:
    paths: [.github/workflows/charm-check-libs.yaml, server/charm/**]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Check Charm Libraries
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write  # necessary to add library status label
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Check libraries
        uses: canonical/charming-actions/check-libraries@bc8d4ee58ddf99c6f13fc80e8a14dfe1e68a8ea6 # 2.7.0
        with:
          charm-path: server/charm
          credentials: ${{ secrets.CHARMHUB_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
