name: Publish OpenAPI on GitHub Pages
on:
  push:
    branches:
      - main
    paths:
      - server/**
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-openapi-html:
    name: Deploy OpenAPI documentation to GitHub Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: [self-hosted, linux, large, noble, x64]
    defaults:
      run:
        working-directory: server
    permissions:
      contents: read
      pages: write  # necessary to create gh pages
      id-token: write  # necessary to request openid connect jwt token
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/configure-pages@v5
      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"
      - run: mkdir -p dist
      - run: |
          npx @redocly/cli build-docs ./schemas/openapi.yaml -o ./dist/index.html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./server/dist"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
