name: Run integration tests
on:
  push:
    branches: [ main ]
    paths:
      - server/**
      - client/**
      - tests/**
      - ".github/workflows/run_integration_tests.yaml"
  pull_request:
    branches: [ main ]
    paths:
      - server/**
      - client/**
      - tests/**
      - ".github/workflows/run_integration_tests.yaml"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: [self-hosted, linux, large, noble, x64]
    defaults:
      run:
        working-directory: integration-tests
    steps:
    - uses: actions/checkout@v4
    - name: Create Docker config with mirror
      run: |
        MIRROR_URL="${DOCKERHUB_MIRROR:-https://github-runner-dockerhub-cache.canonical.com:5000}"
        mkdir -p ~/.docker
        echo "{\"registry-mirrors\": [\"${MIRROR_URL}\"]}" > ~/.docker/daemon.json
        echo '[registry."docker.io"]' > $GITHUB_WORKSPACE/buildkitd.toml
        echo "  mirrors = [\"${MIRROR_URL}\"]" >> $GITHUB_WORKSPACE/buildkitd.toml
    - name: Set up docker buildx
      uses: docker/setup-buildx-action@v3
      with:
        buildkitd-config: ${{ github.workspace }}/buildkitd.toml
    - name: Install docker compose
      run: |
        sudo apt update
        sudo apt install -y docker-compose-v2
    - name: Build and run integration tests
      run: |
        docker compose up --build --abort-on-container-exit
