name: Run integration tests
on:
  push:
    branches: [ main ]
    paths:
      - server/**
      - client/**
      - tests/**
      - ".github/workflows/run_integration_tests.yaml"
  pull_request:
    branches: [ main ]
    paths:
      - server/**
      - client/**
      - tests/**
      - ".github/workflows/run_integration_tests.yaml"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: [self-hosted, linux, large, noble, x64]
    defaults:
      run:
        working-directory: integration-tests
    steps:
    - uses: actions/checkout@v4
    - name: Install docker compose
      run: |
        sudo apt update
        sudo apt install -y docker-compose-v2
    - name: Build and run integration tests
      run: |
        docker compose up --build --abort-on-container-exit
