name: TiCS
permissions: {}
on:
  workflow_dispatch:
  push:
    branches: [main]
  schedule:
    - cron: "0 0 * * 0"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false
jobs:
  analyze:
    name: TiCS Analysis
    runs-on: [self-hosted, linux, amd64, noble, tiobe]
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - run: sudo snap install --classic just
      - name: Install dependencies
        run: |
          just --yes client::setup
          sudo apt-get install -y pipx python3-maturin

      # Client
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # v1
        with:
          toolchain: stable
          components: rustfmt, clippy
      - name: Gather coverage (client)
        working-directory: client
        run: just unit --output coverage.xml
      - name: Build (client)
        working-directory: client
        run: just build
      - name: Install (client pybindings)
        working-directory: client
        run: pip install . --break-system-packages

      # Server
      - name: Set up uv
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
      - name: Gather coverage (server)
        working-directory: server
        run: just test
      - name: Install (server)
        working-directory: server
        run: |
          uv export --no-emit-project --frozen --no-hashes --all-groups > requirements.txt
          pip install -r requirements.txt --break-system-packages

      - name: Combine coverage
        run: |
          mkdir .coverage/
          mv client/coverage.xml .coverage/client_coverage.xml
          mv server/coverage/coverage.xml .coverage/server_coverage.xml

      - name: Run TiCS Analysis
        uses: tiobe/tics-github-action@016a4d79f3027fe7b4a2901619a58c745ab7cadf # v3.10.0
        with:
          mode: qserver
          project: hardware-api
          branchdir: .
          viewerUrl: https://canonical.tiobe.com/tiobeweb/TICS/api/cfg?name=default
          ticsAuthToken: ${{ secrets.TICSAUTHTOKEN }}
          installTics: true
